.db "YOU FOUND the SUPER SECreT CHEAT CODE!"
.db " wow. you are super good at finding these."
.db " to see your reward, visit this url: "
.db "https://www.youtube.com/watch?v=oHg5SJYRHA0"
.db " ... see you next!"
